### ISSUE TITLE
_getRotSkyPos warning

### ISSUE THREAD

**Issue by humnaawan** [lsst/sims_utils#33]
`_getRotSkyPos` says that its output diverges from OpSim (something to do with the relationship between rotSkyPos and rotTelPos). Does that mean that this function should not be used to go from rotTelPos to rotSkyPos? If yes, how should we can go from a dithered rotTelPos to a dithered rotSkyPos?

**Comment by danielsf** [comment]
The issue is a bit more subtle than that.

The relationship between rotSkyPos and rotTelPos as encoded in`_getRotSkyPos` and `_getRotTelPos` is correct, however, it depends on the parallactic angle, which depends on time.  OpSim, internally, uses the beginning of the exposure to calculate rotTelPos from rotSkyPos (or vice versa), but lists the middle of the exposure as expMJD so, if you naively took expMJD, and rotTelPos from OpSim and calculated rotSkyPos, you would get something slightly off from the rotSkyPos listed in OpSim.  I suppose it is easy to subtract 15 seconds (or 7.5 seconds...?) from expMJD.  Regardless, you should use `_getRotSkyPos`, you should just be aware of what time you are using to represent the time of the exposure.

**Comment by humnaawan** [comment]
@danielsf thanks for the explanation! Is it possible to add this 15 seconds offset info to the warning? It could be really helpful.
